const MSG = {
  START_SESSION: 'START_SESSION',
  STOP_SESSION: 'STOP_SESSION',
  SESSION_STATUS: 'SESSION_STATUS',
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_STOPPED: 'SESSION_STOPPED',
  SESSION_ERROR: 'SESSION_ERROR',

  MOUSE_MOVE: 'MOUSE_MOVE',
  INFERENCE_RESULT: 'INFERENCE_RESULT',

  START_CAPTURE: 'START_CAPTURE',
  STOP_CAPTURE: 'STOP_CAPTURE',
  CAPTURE_READY: 'CAPTURE_READY',
  CAPTURE_ERROR: 'CAPTURE_ERROR',
};

const SERVER_URL = 'http://localhost:3000';

if (typeof module !== 'undefined') {
  module.exports = { MSG, SERVER_URL };
}
